### ISSUE TITLE
SerializedProperty and MonoScript defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by BlackRece** [SolidAlloy/GenericUnityObjects#10]
After following install instruction, my project returned these errors and I was unable to run my project.
![image](https://user-images.githubusercontent.com/19497851/107853734-86cbcc80-6e0f-11eb-91ec-3978d89de0a8.png)

**Comment by SolidAlloy** [comment]
Thanks for reporting the error! Please provide the following details:
- Version of Unity you are using.
- OS installed on the machine.
- Whether you have **UnityEditor.CoreModule.dll** file in the following folder:  **\<path-to-unity\>**\Editor\Data\Managed\UnityEngine\

Path to Unity is usually like this on Windows: C:\Program Files\Unity\Hub\Editor\2020.2.2f1\

Must be something platform or version-specific. I will check how dependencies have to be reconfigured to handle this case.

**Comment by BlackRece** [comment]
![image](https://user-images.githubusercontent.com/19497851/107933954-569f3d80-6f77-11eb-90ec-f9e3d8a52926.png)
Unity Version 2020.1.4f1
please confirm the file as I don't seem to have a copy of UnityEditor.CoreModule.dll.
I have several copies of UnityEngine.CoreModule.dll files, per version as shown in the screenshot.
![image](https://user-images.githubusercontent.com/19497851/107935367-36707e00-6f79-11eb-80be-6f1c132e7260.png)

**Comment by SolidAlloy** [comment]
Ah, thanks for that. The package works for Unity 2020.2+. Please install 2020.2 and check it there. I have a badge at the top of README that shows what the minimal Unity version is, but I'll add an additional warning to README to make it more clear.

**Comment by BlackRece** [comment]
i must have mis-read the note. sry.

**Comment by SolidAlloy** [comment]
No problem, thanks for pointing out this flaw!
