### ISSUE TITLE
Creating Generic Scriptable Objects with more than 1 Generic Type doesn't allow to select data types outside of Unity's types

### ISSUE THREAD

**Issue by JingHaoYao** [SolidAlloy/GenericUnityObjects#16]
Using 2020.3.16. The dialogue to pick my own project's data types for multiple generic types works for monobehaviours.

**Comment by SolidAlloy** [comment]
Hello, thanks for reporting the issue. It's been fixed, please check it in the new [2.8.1](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.8.1) version

**Comment by JingHaoYao** [comment]
Looks like it's been fixed! Thank you!
