### ISSUE TITLE
Creating Generic Monobehaviours Dialogue doesn't appear

### ISSUE THREAD

**Issue by JingHaoYao** [SolidAlloy/GenericUnityObjects#18]
Hi, I'm working with a few others on a project and we've found this package to solve most of our design and architecture issues. When I push the files (including those in the GenericUnityObjects folder) and my team member pulls it, they aren't able to add generic monobehaviours via the add component button. ScriptableObjects from the create asset menu work however.

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the issue, I will investigate it. I noticed a similar issue with ScriptableObjects before and fixed it, so it's nice to know they are working well

**Comment by SolidAlloy** [comment]
It had to do with AssetDatabase not importing MonoScript inside the generated .dll files after pulling changes from git. I added a reimport of the failed .dll files, so it should be working fine now. Please check in [2.10.0](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.10.0)
