### ISSUE TITLE
MissingReferenceException: The variable TriangleRight of EditorIconsDatabase doesn't exist anymore

### ISSUE THREAD

**Issue by JingHaoYao** [SolidAlloy/GenericUnityObjects#19]
Hi, got this bug on a mac version of Unity. 

MissingReferenceException: The variable TriangleRight of EditorIconsDatabase doesn't exist anymore.
You probably need to reassign the TriangleRight variable of the 'EditorIconsDatabase' script in the inspector.
UnityEngine.Texture.get_width () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Graphics/Texture.bindings.cs:38)
SolidUtilities.Editor.Helpers.EditorIconsRelated.EditorIcon.GetIconWithMaterial (UnityEngine.Material material) (at Library/PackageCache/com.solidalloy.util@0547b4d844/Editor/Helpers/EditorIconsRelated/EditorIcon.cs:39)
SolidUtilities.Editor.Helpers.EditorIconsRelated.EditorIcon..ctor (UnityEngine.Texture2D icon) (at Library/PackageCache/com.solidalloy.util@0547b4d844/Editor/Helpers/EditorIconsRelated/EditorIcon.cs:29)
SolidUtilities.Editor.Helpers.EditorIcons..cctor () (at Library/PackageCache/com.solidalloy.util@0547b4d844/Editor/Helpers/EditorIcons.cs:30)
Rethrow as TypeInitializationException: The type initializer for 'SolidUtilities.Editor.Helpers.EditorIcons' threw an exception.
TypeReferences.Editor.TypeDropdown.SelectionNode.DrawNodeContent (System.Int32 indentLevel, System.Int32 raiseText) (at Library/PackageCache/com.solidalloy.type-references@3c01f3ad0f/Editor/TypeDropdown/SelectionNode.cs:204)
TypeReferences.Editor.TypeDropdown.SelectionNode.Draw (System.Int32 indentLevel, UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@3c01f3ad0f/Editor/TypeDropdown/SelectionNode.cs:238)
TypeReferences.Editor.TypeDropdown.SelectionNode.DrawSelfAndChildren (System.Int32 indentLevel, UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@3c01f3ad0f/Editor/TypeDropdown/SelectionNode.cs:163)
TypeReferences.Editor.TypeDropdown.SelectionTree.DrawTree (UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@3c01f3ad0f/Editor/TypeDropdown/SelectionTree.cs:204)
TypeReferences.Editor.TypeDropdown.SelectionTree.Draw () (at Library/PackageCache/com.solidalloy.type-references@3c01f3ad0f/Editor/TypeDropdown/SelectionTree.cs:94)
TypeReferences.Editor.TypeDropdown.DropdownWindow.DrawContent () (at Library/PackageCache/com.solidalloy.type-references@3c01f3ad0f/Editor/TypeDropdown/DropdownWindow.cs:174)
TypeReferences.Editor.TypeDropdown.DropdownWindow.OnGUI () (at Library/PackageCache/com.solidalloy.type-references@3c01f3ad0f/Editor/TypeDropdown/DropdownWindow.cs:119)
UnityEditor.HostView.OldOnGUI () (at /Users/bokken/buildslave/unity/build/Editor/Mono/HostView.cs:225)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:353)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:663)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:530)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Single pixelsPerPoint, System.Exception& immediateException) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRenderer/UIRenderers.cs:114)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRChainBuilder.cs:510)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRRepaintUpdater.cs:62)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/VisualTreeUpdater.cs:83)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Panel.cs:829)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Panel.cs:865)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:441)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:209)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:74)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:28)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

Also wanted to thank you for your responsiveness on the other tickets I've made!

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting it. I never experienced this on Windows, so it's probably platform-dependent. Please provide me with the following information:
- Does the _triangle_right_16.png_ file exist at the _SolidUtilities/Editor/Helpers/EditorIconsRelated/_ path?
- Open the _Editor Icons Database.asset_ in a text editor. Is the GUID on the "TriangleRight" line the same as in the _triangle_right_16.png.meta_ file?

My guess is either Unity Editor on MacOS didn't import the image at all or changed its meta during the import

**Comment by JingHaoYao** [comment]
Hi, yes to both questions
![image](https://user-images.githubusercontent.com/23221908/135133231-81ea076b-5593-4349-a05a-871f3b0d1135.png)
![image](https://user-images.githubusercontent.com/23221908/135133250-f507bfb5-efbe-405c-828c-c989d505dd76.png)

**Comment by SolidAlloy** [comment]
Hi, thanks for the screenshots. That's weird, so if the reference is not broken, then is the texture somehow destroyed before accessing it? I have no idea other than this.

Anyway, I added a bunch of checks and workarounds that should protect us against MissingReferenceException. Please check if the error is absent in the [2.10.3](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.10.3) version
