### ISSUE TITLE
Type is not a supported pptr value exception

### ISSUE THREAD

**Issue by JingHaoYao** [SolidAlloy/GenericUnityObjects#21]
Hi, whenever I try to expose a parameter in a function to the inspector, I get the following exception:

![image](https://user-images.githubusercontent.com/23221908/135551300-46e889c3-b43e-4968-9a62-0d0c5647d001.png)

type is not a supported pptr value
UnityEditor.SerializedProperty:set_objectReferenceValue (UnityEngine.Object)
GenericUnityObjects.UnityEditorInternals.GenericUnityEventDrawer:DrawEvent (UnityEngine.Rect,int,bool,bool)
UnityEditorInternal.ReorderableList:DoListElements (UnityEngine.Rect,UnityEngine.Rect)
UnityEditorInternal.ReorderableList:DoList (UnityEngine.Rect,UnityEngine.Rect)
UnityEditorInternal.ReorderableList:DoList (UnityEngine.Rect)
UnityEditorInternal.UnityEventDrawer:OnGUI (UnityEngine.Rect)
UnityEditorInternal.UnityEventDrawer:OnGUI (UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent)
UnityEditor.PropertyHandler:OnGUI (UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent,bool)
UnityEditorInternal.ReorderableList/Defaults:DrawElement (UnityEngine.Rect,UnityEditor.SerializedProperty,object,bool,bool,bool,bool)
UnityEditorInternal.ReorderableList:DoListElements (UnityEngine.Rect,UnityEngine.Rect)
UnityEditorInternal.ReorderableList:DoList (UnityEngine.Rect,UnityEngine.Rect)
UnityEditorInternal.ReorderableListWrapper:Draw (UnityEngine.GUIContent,UnityEngine.Rect,UnityEngine.Rect,bool)
UnityEditor.EditorGUILayout:PropertyField (UnityEditor.SerializedProperty,bool,UnityEngine.GUILayoutOption[])
GenericUnityObjects.Editor.GenericUnityObjectEditor:OnInspectorGUI () (at Library/PackageCache/com.solidalloy.generic-unity-objects@3a065c7dbe/Editor/Drawers/GenericUnityObjectEditor.cs:59)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by SolidAlloy** [comment]
Thanks for reporting the issue. It's been fixed in [2.10.5](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.10.5)
