### ISSUE TITLE
NRE when opening the type dropdown menu to create a generic object

### ISSUE THREAD

**Issue by JingHaoYao** [SolidAlloy/GenericUnityObjects#25]
Error log:
NullReferenceException: Object reference not set to an instance of an object
SolidUtilities.Editor.Helpers.EditorIconsRelated.EditorIcon..ctor (UnityEngine.Texture2D icon) (at Library/PackageCache/com.solidalloy.util@d1a2bc28ba/Editor/Helpers/EditorIconsRelated/EditorIcon.cs:28)
SolidUtilities.Editor.Helpers.EditorIcons..cctor () (at Library/PackageCache/com.solidalloy.util@d1a2bc28ba/Editor/Helpers/EditorIcons.cs:45)
Rethrow as TypeInitializationException: The type initializer for 'SolidUtilities.Editor.Helpers.EditorIcons' threw an exception.
TypeReferences.Editor.TypeDropdown.SelectionNode.DrawTriangleIcon (UnityEngine.Rect triangleRect) (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/SelectionNode.cs:285)
TypeReferences.Editor.TypeDropdown.SelectionNode.DrawNodeContent (System.Int32 indentLevel, System.Int32 raiseText) (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/SelectionNode.cs:202)
TypeReferences.Editor.TypeDropdown.SelectionNode.Draw (System.Int32 indentLevel, UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/SelectionNode.cs:267)
TypeReferences.Editor.TypeDropdown.SelectionNode.DrawSelfAndChildren (System.Int32 indentLevel, UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/SelectionNode.cs:161)
TypeReferences.Editor.TypeDropdown.SelectionTree.DrawTree (UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/SelectionTree.cs:205)
TypeReferences.Editor.TypeDropdown.SelectionTree.Draw () (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/SelectionTree.cs:94)
TypeReferences.Editor.TypeDropdown.DropdownWindow.DrawContent () (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/DropdownWindow.cs:106)
TypeReferences.Editor.TypeDropdown.DropdownWindow.OnGUI () (at Library/PackageCache/com.solidalloy.type-references@e3adbbb8b5/Editor/TypeDropdown/DropdownWindow.cs:64)
UnityEditor.HostView.OldOnGUI () (at /Users/bokken/buildslave/unity/build/Editor/Mono/HostView.cs:240)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:366)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:676)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/IMGUIContainer.cs:543)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Single pixelsPerPoint, System.Exception& immediateException) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRenderer/UIRenderers.cs:132)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRRenderChain.cs:490)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Renderer/UIRRepaintUpdater.cs:76)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/VisualTreeUpdater.cs:155)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Panel.cs:942)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/Panel.cs:985)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:446)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:209)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:74)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Core/UIElementsUtility.cs:28)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

A friend of mine using mac has been getting this error.

**Comment by SolidAlloy** [comment]
I remember you reported this issue before. I checked it again and noticed something in [the screenshot](https://github.com/SolidAlloy/GenericUnityObjects/issues/19#issuecomment-929415727) - the icon of triangle_right_16.png looks like an icon of a broken image. Here's how it looks on Windows on my end:
![image](https://user-images.githubusercontent.com/22909454/138526433-f5e58024-a73d-4d1b-9b99-bf6f78957946.png)
Is there any warning in the inspector when you select the image? Or does a normal texture inspector show up?

**Comment by SolidAlloy** [comment]
I replaced the image asset with a constant base64 string to avoid any kind of interference from Unity. Your friend can try the **2.11.3** version now. But it's still interesting whether Unity on Mac reported any warning for the image.

**Comment by JingHaoYao** [comment]
Hey thanks! I'll get my friend to try this, and I'll get back to you then.

**Comment by SolidAlloy** [comment]
Hi, have you got any news from your friend? I'll close the issue for now, feel free to reopen it if the bug persists
