### ISSUE TITLE
DirectoryNotFoundException when trying to create scriptable objoct asset

### ISSUE THREAD

**Issue by bjornicus** [SolidAlloy/GenericUnityObjects#28]
I installed the packages into my project (tried by using upm-cli and by adding the git urls with the same result).  I then defined a new class inheriting from GenericScriptableObject (I also tried importing the sample).  When I use the menu to create a new asset and choose a class for the generic parameter it fails to create the asset and the consul shows the below stack trace.  

The directory structure does exist with things in it, up to the "ScriptableObjects" directory, which does not exist. 

I'm on a MacBook running unity 2021.2.7f1

`DirectoryNotFoundException: Could not find a part of the path '/Users/bjorn/MyProject/Assets/Plugins/GenericUnityObjects/Assemblies/ScriptableObjects'.
System.IO.Enumeration.FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
System.IO.Enumeration.FileSystemEnumerator`1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
System.IO.Enumeration.FileSystemEnumerable`1+DelegateEnumerator[TResult]..ctor (System.IO.Enumeration.FileSystemEnumerable`1[TResult] enumerable) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
System.IO.Enumeration.FileSystemEnumerable`1[TResult]..ctor (System.String directory, System.IO.Enumeration.FileSystemEnumerable`1+FindTransform[TResult] transform, System.IO.EnumerationOptions options) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos (System.String directory, System.String expression, System.IO.EnumerationOptions options) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
System.IO.DirectoryInfo.InternalEnumerateInfos (System.String path, System.String searchPattern, System.IO.SearchTarget searchTarget, System.IO.EnumerationOptions options) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
System.IO.DirectoryInfo.GetFiles (System.String searchPattern, System.IO.EnumerationOptions enumerationOptions) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
System.IO.DirectoryInfo.GetFiles (System.String searchPattern) (at <bd21fd595d394493a51e7c79b5fef9e0>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFiles(string)
GenericUnityObjects.Editor.Util.ConcreteClassCreator`1[TObject].GetConcreteClassAssemblyName (System.Type genericTypeWithoutArgs, System.Type[] genericArgs, System.String oldAssemblyName) (at Library/PackageCache/com.solidalloy.generic-unity-objects@2.13.1/Editor/Util/ConcreteClassCreator.cs:125)
GenericUnityObjects.Editor.Util.ConcreteClassCreator`1[TObject].CreateConcreteClassAssembly (System.Type genericTypeWithoutArgs, System.Type[] argumentTypes) (at Library/PackageCache/com.solidalloy.generic-unity-objects@2.13.1/Editor/Util/ConcreteClassCreator.cs:80)
GenericUnityObjects.Editor.Util.ConcreteClassCreator`1[TObject].CreateConcreteClass (System.Type genericTypeWithoutArgs, System.Type[] argumentTypes) (at Library/PackageCache/com.solidalloy.generic-unity-objects@2.13.1/Editor/Util/ConcreteClassCreator.cs:29)
GenericUnityObjects.Editor.ScriptableObjects.GenericSOCreator.CreateAssetInteractively (System.Type genericTypeWithoutArgs, System.Type[] genericArgs, System.String fileName) (at Library/PackageCache/com.solidalloy.generic-unity-objects@2.13.1/Editor/ScriptableObjects/GenericSOCreator.cs:117)
GenericUnityObjects.Editor.ScriptableObjects.GenericSOCreator+<>c__DisplayClass5_0.<CreateAsset>b__0 (System.Type[] genericArgs) (at Library/PackageCache/com.solidalloy.generic-unity-objects@2.13.1/Editor/ScriptableObjects/GenericSOCreator.cs:35)
GenericUnityObjects.Editor.ScriptableObjects.SelectionWindow.OneTypeSelectionWindow+<>c__DisplayClass2_0.<GetSelectionTree>b__0 (System.Type type) (at Library/PackageCache/com.solidalloy.generic-unity-objects@2.13.1/Editor/ScriptableObjects/SelectionWindow/OneTypeSelectionWindow.cs:35)
TypeReferences.Editor.TypeDropdown.SelectionTree.FinalizeSelection () (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/SelectionTree.cs:64)
TypeReferences.Editor.TypeDropdown.SelectionNode.HandleMouseEvents () (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/SelectionNode.cs:226)
TypeReferences.Editor.TypeDropdown.SelectionNode.Draw (System.Int32 indentLevel, UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/SelectionNode.cs:269)
TypeReferences.Editor.TypeDropdown.SelectionNode.DrawSelfAndChildren (System.Int32 indentLevel, UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/SelectionNode.cs:161)
TypeReferences.Editor.TypeDropdown.SelectionTree.DrawTree (UnityEngine.Rect visibleRect) (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/SelectionTree.cs:205)
TypeReferences.Editor.TypeDropdown.SelectionTree.Draw () (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/SelectionTree.cs:94)
TypeReferences.Editor.TypeDropdown.DropdownWindow.DrawContent () (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/DropdownWindow.cs:106)
TypeReferences.Editor.TypeDropdown.DropdownWindow.OnGUI () (at Library/PackageCache/com.solidalloy.type-references@2.11.5/Editor/TypeDropdown/DropdownWindow.cs:64)
UnityEditor.HostView.OldOnGUI () (at /Users/bokken/buildslave/unity/build/Editor/Mono/HostView.cs:266)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:372)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:687)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:659)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:652)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:618)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:607)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/IMGUIContainer.cs:535)
UnityEngine.UIElements.EventDispatchUtilities.PropagateEvent (UnityEngine.UIElements.EventBase evt) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Events/IEventDispatchingStrategy.cs:113)
UnityEngine.UIElements.MouseEventDispatchingStrategy.SendEventToRegularTarget (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Events/MouseEventDispatchingStrategy.cs:35)
UnityEngine.UIElements.MouseEventDispatchingStrategy.SendEventToTarget (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Events/MouseEventDispatchingStrategy.cs:26)
UnityEngine.UIElements.MouseEventDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel iPanel) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Events/MouseEventDispatchingStrategy.cs:19)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs:381)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs:344)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs:306)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs:270)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs:75)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs:372)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/EventDispatcher.cs:222)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/Panel.cs:417)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:468)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:211)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:74)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Core/UIElementsUtility.cs:28)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
`

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the issue. It's been fixed, so please try the [2.14.1](https://github.com/SolidAlloy/GenericUnityObjects/releases/tag/2.14.1) version of the package.
