### ISSUE TITLE
Missing com.madsbangh.easybuttons dependency

### ISSUE THREAD

**Issue by bjornicus** [SolidAlloy/GenericUnityObjects#29]
after doing `openupm install com.solidalloy.generic-unity-objects` I was getting errors in the console about missing EasyButtons.  `openupm install com.madsbangh.easybuttons` seems to have solved it but that should be added to the README or ideally just specified as a dependency if that's possible.

**Comment by SolidAlloy** [comment]
Hi, thanks for submitting the issue. It's an optional dependency, but I forgot to disable the code that uses EasyButtons with a preprocessor directive. It's fixed now, so you no longer need EasyButtons installed to use GenericUnityObjects.
