### ISSUE TITLE
The type or namespace name 'MissingScriptType' could not be found

### ISSUE THREAD

**Issue by thewhitewayofdelight** [SolidAlloy/GenericUnityObjects#32]
Hello there, again :D

I just installed the newest version of this package on a Windows machine. 
And this error shows up

![image](https://user-images.githubusercontent.com/87333145/156920061-4bc24218-2918-4e4c-89e3-027d7c86e16d.png)

Any idea??

P.S.
I have already disabled the Assembly Version Validation setting.

Thank you

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the issue. My bad, I forgot to wrap one line in a conditional directive :P Fixed now, please update the package.
