### ISSUE TITLE
Creating GenericSO via Createable attribute always fail for the first time

### ISSUE THREAD

**Issue by thewhitewayofdelight** [SolidAlloy/GenericUnityObjects#33]
**Description**
If I have a new type of generic SO, creating it via "+" button on the Inspector always fail for the first try. The second time I do that, the creation always succeed. Anyway, here are the error messages. 

**Steps to reproduce**
1. Create generic SO class  `(SO<T> : GenericScriptableObject)`
2. Create a class that reference to the newly created generic SO class `[Creatable] public SO<MonoBehaviour> Test`
3. Create the instance of `SO<MonoBehaviour>` on the Unity Inspector with the "+" button.
4. Notice that when first time creating it, it throw error 
5. When you click that button again, it succeed!

** Still usable tho, but of course, always suceed on the first try is easier :)

<img width="493" alt="image" src="https://user-images.githubusercontent.com/87333145/157303415-56e86f65-eb18-4a18-bc70-458951211e7f.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/87333145/157303479-71e8bb4a-0571-44ad-b241-e2ea5eafc7f0.png">

Thank you!

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the bug! It has been fixed, please update the package and try again
