### ISSUE TITLE
The type or namespace name 'AssemblyBuilder' could not be found

### ISSUE THREAD

**Issue by MisterProjectLC** [SolidAlloy/GenericUnityObjects#34]
![image](https://user-images.githubusercontent.com/30096102/160733666-0824cac3-22fd-4e49-b035-7eb67de65c49.png)
Installed the package on Windows, got these two errors. Visual Studio doesn't point out any errors, though.
I have disabled the Assembly Version Validation prior to downloading this package.

**Comment by SolidAlloy** [comment]
Hi, it looks like you are using Unity 2020. Please switch from .NET Standard to .NET Framework in Project Settings -> Player. This requirement is only for Unity 2020. Starting from Unity 2021, there is no need to switch to .NET Framework

**Comment by mnicolas94** [comment]
I'm using Unity 2021.1.13f1 and also got that error. I fixed it, as you said, changing from .NET Standard 2.0 to .NET 4.x in player settings

**Comment by SolidAlloy** [comment]
Yes, I overlooked the fact that the switch to .NET Standard 2.1 happened in 2021.2, so .NET 4.x must still be used in 2021.1. Good to know you figured it out!
